name: Deploy Java App to AWS ASG

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Java
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17' # Adjust based on your application's requirements

    - name: Build Java Application
      run: |
        mvn package -DskipTests # Use Gradle if applicable

  
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Create AMI with Updated Java App
      run: |
        INSTANCE_ID=$(aws ec2 describe-instances --filters "Name=tag:Name,Values=product-app-soham" --query "Reservations[0].Instances[0].InstanceId" --output text)
        AMI_ID=$(aws ec2 create-image --instance-id $INSTANCE_ID --name "product-app-soham-$(date +%Y%m%d%H%M%S)" --no-reboot --query "ImageId" --output text)
        echo "AMI_ID=$AMI_ID" >> $GITHUB_ENV

    - name: Update Launch Template with New AMI
      run: |
        #LAUNCH_TEMPLATE_NAME="soham-test-template"
        #LAUNCH_TEMPLATE_ID=$(aws ec2 describe-launch-templates --filters "Name=launch-template-name,Values=$LAUNCH_TEMPLATE_NAME" --query "LaunchTemplates[0].LaunchTemplateId" --output text)
        LAUNCH_TEMPLATE_ID=$(aws ec2 describe-launch-templates --query "LaunchTemplates[7].LaunchTemplateId" --output text)
        aws ec2 create-launch-template-version \
          --launch-template-id $LAUNCH_TEMPLATE_ID \
          --source-version 1 \
          --launch-template-data '{"ImageId":"'"$AMI_ID"'"}'
        aws ec2 modify-launch-template \
          --launch-template-id $LAUNCH_TEMPLATE_ID \
          --default-version 5

    - name: Trigger ASG Instance Refresh
      run: |
        aws autoscaling start-instance-refresh --auto-scaling-group-name product-app-soham --preferences '{"MinHealthyPercentage": 90}'
